name: Publish Dokka HTML to GitHub Pages

on:
  push:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build Dokka HTML
        run: ./gradlew dokkaHtmlMultiModule

      - name: Move Dokka HTML to Docs Directory
        run: |
          mkdir -p docs
          mv build/dokka/htmlMultiModule/* docs/
        if: success()

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: docs
